- cmd/build.go
- cmd/init.go
Resolves https://github.com/onepanelio/core/issues/92
> feat(https): https and certificate manager options 

- cmd/init.go
Resolves https://github.com/onepanelio/core/issues/98
> feat(gpu): add gpu-device-plugins flag

- cmd/apply.go
> feat: show url for deployment once app is completely launched.

- cmd/apply.go
- util/kubectl.go
- This code will output the IP, depending on what's uncommented.
- Leaving in progress code for investigation
> Getting istio ingress gateway external ip

- util/kubeconfig.go
- Code should refresh the token.
closes #https://github.com/onepanelio/core/issues/87
> Adding code to handle an expire GKE token.

- cmd/apply.go
- cmd/status.go
- util/status.go
> feat: Check namespaces based on provider

- cmd/build.go
- util/dynamic_yaml.go
Parent: https://github.com/onepanelio/core/issues/114
Closes: https://github.com/onepanelio/core/issues/114
> Feature/core.114 move.defaultnamespace

- cmd/build.go
closes #https://github.com/onepanelio/core/issues/109
> Feature/core.109 sys.env.vars

- cmd/apply.go
- cmd/build.go
- cmd/init.go
- Sets the Images to develop (for core and core-ui)
- Sets the pull policy for core and core-ui to "Always"
closes https://github.com/onepanelio/core/issues/141
> Added "--develop" flag.

- cmd/build.go
- Telling code to look for new s3 place.
closes https://github.com/onepanelio/core/issues/158
> Updating validation checking and flatMap access.

- cmd/apply.go
- cmd/build.go
closes https://github.com/onepanelio/core/issues/160
> Using URL instead of Host.

- cmd/build.go
> fix: don't quote boolean values

- util/kubectl.go
a hostname.
closes https://github.com/onepanelio/core/issues/259
> Adding code to handle EKS Elastic Load Balancer not having an IP, but

- CONTRIBUTING.md
- Makefile
> standardize version and tags

- cmd/apply.go
**What type of PR is this?**
/kind bug
Fixes onepanelio/core#324
> fix: display correct status command

- cmd/app.go
- cmd/apply.go
- cmd/build.go
- cmd/init.go
- go.mod
- util/kubectl.go
- util/url.go
> feat: local deployments with istio

- cmd/init.go
- Updated relevant uses and documentation
Changing the flag for `--dns-provider` to `--cert-manager-dns-provider`
Fixes onepanelio/core#358
> feat: Changing flag from `--dns-provider` to `--cert-manager-dns-provider`

- cmd/init.go
> Revert "feat: Changing flag from `--dns-provider` to `--cert-manager-dns-provider`"

- cmd/build.go
- cmd/build_test.go
- go.mod
- util/dynamic_yaml.go
Extend options field in nodePool to take resource quotas.
Fixes onepanelio/core#392
> feat: Support resource limits in nodePoolOptions

- cmd/apply.go
- cmd/build.go
- cmd/init.go
- template/builder.go
> feat: Adding code to make the filepaths OS agnostic.

- cmd/apply.go
- cmd/build.go
- cmd/init.go
- template/builder.go
> fix: Make sure S3 secret placeholder is replaced properly

- cmd/build.go
> fix: Use consistent naming convention for GCS artifactRepository secret key

- cmd/build.go
Fix issue with using gcs as a cloud storage provider
Fixes onepanelio/core#521
> fix: issue with using gcs as a cloud storage provider

- cmd/init.go
Fixes an issue where artifactRepositoryProvider was not required in the cli - it needs to be for it to function properly.
Fixes onepanelio/core#531
> fix: issue where artifactRepositoryProvider was not required in cli

- util/kubeconfig.go
> feat: Updating `opctl auth token` to return the token for the admin service account.

- cmd/init.go
> feat: added cluster autoscalar for eks

- manifest/builder.go
Update code to exclude argo components that don't need to be included.
> fix: removed source argo component from manifest

- cmd/init.go
> feat: Add GKE NVIDIA driver overlay

- cmd/init.go
> fix: clean up path of cli_config file in init command

- Makefile
- go.mod
> feat: dockerized command to build CLI and fixed issue windows build

- cmd/build.go
> fix: rename build command --dev flag to --latest

- cmd/apply.go
- cmd/build.go
- cmd/init.go
- util/dynamic_yaml.go
- util/randomness.go
> feat: update gcs to use minio

- cmd/init.go
> fix: added gcs to list of acceptable artifact repository provider types

- cmd/build.go
> feat: add default workflow engine runtime executor if one is not present

- cmd/app.go
- cmd/apply.go
- cmd/auth.go
- util/dynamic_yaml.go
- util/kubeconfig.go
- util/kubectl.go
> feat: detect microk8s provider in apply/app status

- cmd/app.go
- cmd/apply.go
- util/kubectl.go
> fix: issue where some clusters took a while to get an external ip

- cloud/storage/storage.go
- cmd/app.go
- cmd/build.go
- cmd/init.go
- cmd/root.go
- util/kubectl.go
> feat: add support to expose minio

- cmd/init.go
> fix: kfserving requires cert-manager

- cmd/build.go
- cmd/init.go
> feat: support kfserving without https

- util/kubectl.go
> fix: add model serving url to output for microk8s
