cmd/apply.go
cmd/build.go

This fixes the issue with the "Building..." messages being repeated twice and moves the "Starting deployment..." message so it's displayed sooner.

feat(cli): Move build and deployment messages to correct place

---

.gitignore
cmd/apply.go
cmd/build.go
cmd/init.go
cmd/root.go
main.go

This moves all generated files except for `params.yaml` and `config.yaml` to `.onepanel` folder.

feat: move generated files to .onepanel folder

---

cmd/build.go
cmd/init.go
util/url.go

updated references from application.cloud.insecure to application.insecure
updated references to cloud variables to be loaded from new file in manifests.
closes onepanelio/core#287 (along with manifests PR)

update: removed cloud settings

---

cmd/build.go

closes onepanelio/core#307 (along with new Core-UI and Core dev branches)

update: develop -> dev for images.

---

cmd/init.go
manifest/source.go

Fixes the manifests not changing between CLI releases.
If you started with CLI 0.9.0, used `init`, you would get v.0.9.0 as your git source.
If you updated to CLI 0.10.0, used `init`, you would still have the v.0.9.0 as your git source.
With this change, the git source will properly match the CLI version.
- Note that this means a tag of "latest" will not work unless CLI version is set to "latest"
- If `cli_config.yaml` has a source of "directory", the CLI tag is ignored. The directory will continue to be used.
Fixes onepanelio/core#344

fix: core.344 manifests.cache.issue

---

util/kubectl.go

Fixes a regression. The DNS and IP information was not output when `opctl app status` was executed.
- Specifically, for cloud providers.
Fixes onepanelio/core#375
To test, have your kubectl pointing to a cloud deployment.
If you have the yaml key ```application.provider``` in your params.yaml, set it to a cloud provider such as `aks`.
If you do not have that key, the cli command will default to DNS and IP output.

fix: core.375 app.status.ip.address

---

cmd/app.go

Adds `kubectl` command to run for checking status of all pods

feat: Add troubleshooting info

---

cmd/build.go
cmd/init.go
files/files.go
manifest/builder.go
util/dynamic_yaml.go

Adds support for services
Fixes onepanelio/core#395

feat: add services support for cli

---

cmd/app.go
cmd/build.go
cmd/build_test.go
cmd/init.go
files/files.go
go.mod
manifest/builder.go
util/dynamic_yaml.go

Adds support for components.
Fixes onepanelio/core#395

feat: Add cli support for components

---

cmd/init.go

Fixes an issue where not specifying an artifact repository gave you an empty curly brace result
Fixes onepanelio/core#480

fix: no artifact repository emitted an empty key in params.yaml

---

cmd/init.go

fix: error check for modeldb and non s3 cloud storage

---

cmd/init.go

Fixes an issue where duplicate entries appeared in params.yaml
Fixes onepanelio/core#481
To reproduce (before this fix)
Run: 
```init --provider aks --enable-https --enable-cert-manager --dns-provider route53 --services modeldb --artifact-repository-provider s3```
Then
```init --provider aks --enable-https --enable-cert-manager --dns-provider route53 --services modeldb ```
The bottom two entries are duplicates.

fix: Issue where duplicate entries appeared in params.yaml

---

util/kubectl.go

When deploying on minikube or microk8s, display the correct windows hosts path (for windows 10)
Fixes onepanelio/core#532

feat: display correct hosts file path on windows 10

---

go.mod
go.sum

Updates the `go.mod` reference to onepanel core to be 0.12.0.
This fixes a compilation issue.

fix: update onepanel core api version

---

files/network.go

Adds the user-agent header for github downloads. This fixes an issue where github downloads didn't work sometimes.
https://docs.github.com/en/rest/overview/resources-in-the-rest-api#user-agent-required
Fixes onepanelio/core#552

fix: issue where downloading github zips sometimes didn't work

---

cmd/auth.go
util/kubeconfig.go

- If no parameter is passed in, 'admin' is default
-
Fixes onepanelio/core#664
Run `auth token --help` to see parameter help.

feat: Adding support for "--username / -u" parameter in `auth token` command.

---

util/kubeconfig.go

fix: Removing in.ExecProvider to prevent the wrong token being grabbed when using EKS clusters.

---

cmd/init.go
util/dynamic_yaml.go

Adds the init command used to be output in params.yaml.
Sample:
```
application:...
```
Fixes onepanelio/core#666

feat: added comment used in init to be output to params.yaml

---

cmd/init.go

Updates and fixes CLI messages to match documentation.

chore: Update CLI messages

---

manifest/builder.go

This fixes `common\argo\source\base` being included during `opctl init`.

fix: Using filepath, since it creates platform specific filepath separators.

---

cmd/apply.go
cmd/build.go
manifest/manifest.go

Catches errors with params.yaml when the default namespace is blank, missing, or a reserved namespace.
Fixes onepanelio/core#748

fix: catch errors with defaultNamespace in params.yaml

---

cmd/apply.go
cmd/build.go
cmd/delete.go
manifest/manifest.go
util/kubectl.go
util/status.go

Adds a basic delete command.
Fixes onepanelio/core#270
This does not wait to see if all resources have been deleted, so it may take the cluster a few seconds to delete everything.
Use in conjunction with: https://github.com/onepanelio/manifests/pull/102

feat: cli delete command

---

cloud/storage/storage.go
cmd/build.go
cmd/init.go
go.mod
util/dynamic_yaml.go

feat: Add azure blob storage support

---

cmd/apply.go
cmd/build.go

feat: rename dev to latest

---

cmd/apply.go
cmd/build.go
cmd/init.go
config/models.go
files/files.go
go.mod
go.sum
manifest/builder.go
util/dynamic_yaml.go

Automatically generates database configuration unless otherwise specified. 
Also, checks if there is already existing database configuration in the cluster and uses that, if applicable.

feat: optional database configuration

---

cmd/init.go
util/kubectl.go

chore: rename model serving flag

---

manifest/manifest.go

When running `opctl apply` or `opctl build` this will check to make sure the `application.fqdn` ends in `application.domain`. If it doesn't, an error message is printed out.
Fixes onepanelio/core#949

feat: make sure fqdn ends in domain
